name: CI/CD

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar
      run: dotnet build --no-restore

    - name: Ejecutar tests
      run: dotnet test --no-build --verbosity normal
